# Generated by Django 5.2 on 2026-06-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSpec',
        ),
    ]
