# Generated by Django 4.2.30 on 2026-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_delete_userspec"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="company_size",
            field=models.CharField(default="무관", max_length=20),
        ),
    ]
