# Generated by Django 5.2 on 2026-06-18 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="language_score",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(
                blank=True, help_text="간단한 자기소개", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="활동명")),
                ("description", models.TextField(blank=True, verbose_name="활동 내용")),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "대내외활동",
                "verbose_name_plural": "대내외활동",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="자격증명")),
                ("issuer", models.CharField(max_length=100, verbose_name="발급기관")),
                ("date_acquired", models.DateField(verbose_name="취득일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "자격증",
                "verbose_name_plural": "자격증",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=100, verbose_name="학교명"),
                ),
                ("major", models.CharField(max_length=100, verbose_name="전공")),
                (
                    "degree",
                    models.CharField(
                        max_length=50, verbose_name="학위 (예: 학사, 석사)"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="입학일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="졸업일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "학력사항",
                "verbose_name_plural": "학력사항",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="프로젝트명")),
                ("description", models.TextField(verbose_name="프로젝트 설명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("url", models.URLField(blank=True, verbose_name="관련 링크")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "프로젝트",
                "verbose_name_plural": "프로젝트",
            },
        ),
    ]
