# Generated by Django 5.2 on 2026-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_education_and_more'),
        ('jobs', '0002_delete_userspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='jobs.skill'),
        ),
    ]
