# Generated by Django 4.2.30 on 2026-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_company_size",
            field=models.CharField(
                choices=[
                    ("대기업", "대기업"),
                    ("중견기업", "중견기업"),
                    ("중소기업", "중소기업"),
                    ("스타트업", "스타트업"),
                    ("무관", "무관"),
                ],
                default="무관",
                max_length=20,
                verbose_name="희망 기업 규모",
            ),
        ),
    ]
